### ISSUE TITLE
Use a wrapper for your mini tests

### ISSUE THREAD

**Issue by eoriont** [RileyPaddock/graph#1]
In your graph.py file, you have a couple mini tests at the bottom of the file. 

(Mini tests being tests not trivial enough to be in a test file but just to show it works)

You should put these in a wrapper because if you ever import graph.py from another file, it will run the tests. The most pythonic wrapper I've found is this:

```
if __name__ == "__main__":
    print("Code goes here")
```

What this does is it will only run the code inside if you are specifically running that file.

**Comment by RileyPaddock** [comment]
Oh I just forgot the tests were there. I will get rid of them but this is a good technique that I will keep for the future.
